"""C target plugin for the fuzzer.

Discovers C function targets via tree-sitter-c, compiles and executes
test harnesses generated by the AI engine, and returns FuzzResult objects
compatible with the existing fuzzer pipeline.

Requires ``DCS_FUZZ_ALLOWED_PLUGINS`` to include ``"c"`` to be loadable.
"""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path
from typing import Any

from deep_code_security.fuzzer.analyzer.c_signature_extractor import (
    extract_c_targets_from_file,
    extract_c_targets_from_source,
)
from deep_code_security.fuzzer.exceptions import ExecutionError, PluginError
from deep_code_security.fuzzer.models import FuzzInput, FuzzResult, TargetInfo
from deep_code_security.fuzzer.plugins.base import TargetPlugin

__all__ = ["CTargetPlugin"]

logger = logging.getLogger(__name__)


class CTargetPlugin(TargetPlugin):
    """C language fuzz target plugin.

    Discovers C function targets from ``.c`` files, validates them, and
    delegates harness execution to CFuzzRunner (Work Group 2).

    The plugin follows the same pattern as PythonTargetPlugin but uses
    the C-specific signature extractor and runner.

    Notes:
        ``file_extensions`` returns a ``tuple`` (immutable) rather than
        the ``list[str]`` declared in the ABC. Both are sequences and the
        return is runtime-compatible. This satisfies the "no mutable default
        arguments" rule (CLAUDE.md).
    """

    def __init__(self) -> None:
        # CFuzzRunner is provided by Work Group 2.  Import lazily so that
        # unit tests can patch the import and this module can be loaded even
        # when c_runner.py has not yet been installed.
        self._runner: Any | None = None
        # Maps function_name -> module_path (absolute .c file path)
        self._target_files: dict[str, str] = {}

    # ------------------------------------------------------------------
    # ABC properties
    # ------------------------------------------------------------------

    @property
    def name(self) -> str:
        """Plugin identifier used by the registry and CLI ``--plugin`` flag."""
        return "c"

    @property
    def file_extensions(self) -> tuple[str, ...]:
        """File extensions handled by this plugin.

        Returns a tuple (immutable) per CLAUDE.md "no mutable default
        arguments" rule.  The ABC declares ``list[str]`` but a tuple is
        compatible at runtime.
        """
        return (".c",)

    # ------------------------------------------------------------------
    # Runner initialisation (lazy)
    # ------------------------------------------------------------------

    def _ensure_runner(self) -> Any:
        """Initialise and return the CFuzzRunner, importing it lazily."""
        if self._runner is None:
            try:
                from deep_code_security.fuzzer.execution.c_runner import CFuzzRunner
            except ImportError as exc:
                raise PluginError(
                    "CFuzzRunner is not available. Ensure the C fuzzer execution "
                    "layer (Work Group 2) has been installed."
                ) from exc
            self._runner = CFuzzRunner()
        return self._runner

    # ------------------------------------------------------------------
    # TargetPlugin interface
    # ------------------------------------------------------------------

    def discover_targets(
        self,
        path: str,
        allow_side_effects: bool = False,
    ) -> list[TargetInfo]:
        """Discover fuzzable C functions in *path*.

        Accepts a single ``.c`` file or a directory; for directories all
        ``.c`` files are scanned recursively.

        Args:
            path: Path to a ``.c`` file or a directory containing ``.c``
                files.
            allow_side_effects: Unused for C targets (kept for ABC compat).

        Returns:
            List of TargetInfo objects for each fuzzable function found.

        Raises:
            PluginError: If *path* is not a valid C target.
        """
        if not self.validate_target(path):
            raise PluginError(f"Not a valid C target: {path}")

        p = Path(path)
        c_files: list[Path]

        if p.is_file():
            c_files = [p]
        else:
            c_files = sorted(p.rglob("*.c"))

        targets: list[TargetInfo] = []
        for c_file in c_files:
            file_targets = extract_c_targets_from_file(str(c_file))
            for target in file_targets:
                # Record the source file for each function so execute() can
                # pass it to CFuzzRunner.
                self._target_files[target.function_name] = str(c_file)
            targets.extend(file_targets)

        logger.info(
            "Discovered %d fuzzable C target(s) in %s",
            len(targets),
            path,
        )
        return targets

    def execute(
        self,
        fuzz_input: FuzzInput,
        timeout_ms: int,
        collect_coverage: bool = True,
    ) -> FuzzResult:
        """Execute a single C fuzz input via CFuzzRunner.

        The harness source code is carried in
        ``fuzz_input.metadata["harness_source"]``.  The sentinel value in
        ``fuzz_input.args`` (``"'__c_harness__'"``*) is never evaluated.

        ``collect_coverage`` is always passed as ``True`` for C targets
        regardless of the backend type, because gcov data is collected
        inside the container and returned via the JSON IPC protocol (unlike
        Python coverage.py which writes to host-side paths).

        Args:
            fuzz_input: FuzzInput with metadata["harness_source"] set.
            timeout_ms: Execution timeout in milliseconds.
            collect_coverage: Passed through to CFuzzRunner; always True for
                C targets (see plan Section 10).

        Returns:
            FuzzResult with success/exception/traceback/coverage_data fields.

        Raises:
            ExecutionError: If the target function was not discovered or the
                harness source is missing from metadata.
        """
        func_name = fuzz_input.target_function
        target_file = self._target_files.get(func_name)

        if target_file is None:
            raise ExecutionError(
                f"Unknown C target function: {func_name}. "
                "Call discover_targets() first or ensure the function name "
                "matches a discovered target."
            )

        harness_source = fuzz_input.metadata.get("harness_source")
        if not harness_source:
            raise ExecutionError(
                f"No harness_source in fuzz_input.metadata for target {func_name!r}. "
                "The C response parser must populate metadata['harness_source']."
            )

        runner = self._ensure_runner()

        # C targets always collect coverage via gcov inside the container/process
        # (plan Section 10), overriding the orchestrator's collect_coverage heuristic.
        return runner.run(
            fuzz_input=fuzz_input,
            target_file=target_file,
            timeout_ms=timeout_ms,
            collect_coverage=True,
        )

    def validate_target(self, path: str) -> bool:
        """Check whether *path* is a valid C fuzzing target.

        A path is valid if it is:
        - An existing ``.c`` file, **or**
        - An existing directory that contains at least one ``.c`` file.

        On macOS, if SubprocessBackend mode is implied (no ContainerBackend
        configured), a warning is emitted when ``gcc --version`` reports
        Apple Clang, advising the user to use the container backend.

        Args:
            path: Filesystem path to validate.

        Returns:
            ``True`` if the path is a valid C target, ``False`` otherwise.
        """
        p = Path(path)
        if p.is_file():
            if p.suffix == ".h":
                raise PluginError(
                    f"{path}: C fuzzer requires a .c source file with function "
                    "definitions; .h header files are not supported (headers contain "
                    "declarations only, not function bodies that can be compiled and fuzzed)."
                )
            if p.suffix != ".c":
                return False
            self._warn_if_apple_clang()
            return True
        if p.is_dir():
            has_c = any(p.rglob("*.c"))
            if has_c:
                self._warn_if_apple_clang()
            return has_c
        return False

    def set_backend(self, backend: Any) -> None:
        """Set the execution backend on the internal CFuzzRunner.

        Called by FuzzOrchestrator when a specific backend is required (e.g.,
        CContainerBackend for MCP-triggered C fuzz runs).  The runner is
        initialised lazily on first call if it has not been used yet.

        Args:
            backend: An ExecutionBackend-compatible object
                (SubprocessBackend or CContainerBackend).
        """
        runner = self._ensure_runner()
        runner._sandbox.set_backend(backend)
        logger.debug(
            "CTargetPlugin: execution backend set to %s",
            type(backend).__name__,
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def register_target_file(self, function_name: str, target_file: str) -> None:
        """Manually register a target file for a function name.

        Useful for testing without calling discover_targets().

        Args:
            function_name: C function name (unqualified).
            target_file: Absolute path to the ``.c`` source file.
        """
        self._target_files[function_name] = target_file

    @staticmethod
    def _warn_if_apple_clang() -> None:
        """Log a warning when the system gcc is actually Apple Clang.

        On macOS, ``gcc`` is typically a symlink to Apple Clang, which has
        different ASan runtime behaviour and gcov output format.  The primary
        supported path for reliable results is the container backend (Podman).
        """
        try:
            result = subprocess.run(
                ["gcc", "--version"],
                capture_output=True,
                text=True,
                timeout=5,
            )
            if "Apple clang" in result.stdout or "Apple clang" in result.stderr:
                logger.warning(
                    "The 'gcc' binary reports Apple Clang. "
                    "ASan and gcov behaviour may differ from the supported gcc 13 "
                    "container.  Use the container backend (Podman + "
                    "make build-fuzz-c-sandbox) for reliable C fuzzing results."
                )
        except FileNotFoundError:
            logger.warning(
                "gcc not found on PATH. "
                "SubprocessBackend C fuzzing requires gcc. "
                "Use the container backend (Podman + make build-fuzz-c-sandbox) "
                "or install gcc."
            )
        except Exception:
            # Best-effort only — do not fail validate_target() on gcc check errors.
            pass
